# Generated by Django 6.1 on 2026-08-29 16:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("astronomy", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ExoplanetWatchlist",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "exoplanet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="astronomy.exoplanet",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exoplanet_watchlist",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "exoplanet_watchlist",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "exoplanet"), name="uk_ew_user_ep"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="NeoWatchlist",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "neo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="astronomy.neo"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="neo_watchlist",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "neo_watchlist",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "neo"), name="uk_nw_user_neo"
                    )
                ],
            },
        ),
    ]
