# Generated by Django 6.1 on 2026-08-29 16:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="HostStar",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                (
                    "distance_pc",
                    models.DecimalField(
                        blank=True,
                        db_index=True,
                        decimal_places=3,
                        max_digits=12,
                        null=True,
                    ),
                ),
                (
                    "spectral_type",
                    models.CharField(blank=True, max_length=30, null=True),
                ),
                (
                    "temperature_k",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "radius_solar",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=12, null=True
                    ),
                ),
                (
                    "mass_solar",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=12, null=True
                    ),
                ),
                (
                    "metallicity",
                    models.DecimalField(
                        blank=True, decimal_places=5, max_digits=10, null=True
                    ),
                ),
                (
                    "surface_gravity",
                    models.DecimalField(
                        blank=True, decimal_places=5, max_digits=10, null=True
                    ),
                ),
            ],
            options={
                "db_table": "host_star",
            },
        ),
        migrations.CreateModel(
            name="Neo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nasa_id", models.CharField(max_length=20, unique=True)),
                ("name", models.CharField(max_length=100)),
                ("designation", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "absolute_magnitude",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=6, null=True
                    ),
                ),
                (
                    "diameter_min_m",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=14, null=True
                    ),
                ),
                (
                    "diameter_max_m",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=14, null=True
                    ),
                ),
                ("is_hazardous", models.BooleanField(db_index=True, default=False)),
                ("is_sentry_object", models.BooleanField(default=False)),
                ("jpl_url", models.URLField(blank=True, max_length=500, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "neo",
            },
        ),
        migrations.CreateModel(
            name="NeoFetchLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fetch_date", models.DateField(unique=True)),
                ("fetched_at", models.DateTimeField(auto_now_add=True)),
                ("element_count", models.IntegerField(default=0)),
                ("is_success", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "neo_fetch_log",
            },
        ),
        migrations.CreateModel(
            name="Exoplanet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("planet_name", models.CharField(max_length=100, unique=True)),
                (
                    "radius_earth",
                    models.DecimalField(
                        blank=True,
                        db_index=True,
                        decimal_places=6,
                        max_digits=12,
                        null=True,
                    ),
                ),
                (
                    "mass_earth",
                    models.DecimalField(
                        blank=True,
                        db_index=True,
                        decimal_places=6,
                        max_digits=14,
                        null=True,
                    ),
                ),
                (
                    "equilibrium_temp_k",
                    models.DecimalField(
                        blank=True, decimal_places=8, max_digits=10, null=True
                    ),
                ),
                (
                    "orbital_period_days",
                    models.DecimalField(
                        blank=True, decimal_places=8, max_digits=16, null=True
                    ),
                ),
                (
                    "discovery_year",
                    models.SmallIntegerField(blank=True, db_index=True, null=True),
                ),
                (
                    "discovery_method",
                    models.CharField(
                        blank=True, db_index=True, max_length=50, null=True
                    ),
                ),
                (
                    "host_star",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="planets",
                        to="astronomy.hoststar",
                    ),
                ),
            ],
            options={
                "db_table": "exoplanet",
            },
        ),
        migrations.CreateModel(
            name="OrbitalData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("orbit_id", models.CharField(blank=True, max_length=30, null=True)),
                (
                    "orbit_determination_datetime_utc",
                    models.DateTimeField(blank=True, null=True),
                ),
                ("first_observation_date", models.DateField(blank=True, null=True)),
                ("last_observation_date", models.DateField(blank=True, null=True)),
                ("data_arc_days", models.IntegerField(blank=True, null=True)),
                ("observations_used", models.IntegerField(blank=True, null=True)),
                (
                    "eccentricity",
                    models.DecimalField(
                        blank=True, decimal_places=10, max_digits=14, null=True
                    ),
                ),
                (
                    "semi_major_axis_au",
                    models.DecimalField(
                        blank=True, decimal_places=10, max_digits=14, null=True
                    ),
                ),
                (
                    "inclination_deg",
                    models.DecimalField(
                        blank=True, decimal_places=8, max_digits=12, null=True
                    ),
                ),
                (
                    "orbital_period_days",
                    models.DecimalField(
                        blank=True, decimal_places=8, max_digits=16, null=True
                    ),
                ),
                (
                    "perihelion_distance_au",
                    models.DecimalField(
                        blank=True, decimal_places=10, max_digits=14, null=True
                    ),
                ),
                (
                    "aphelion_distance_au",
                    models.DecimalField(
                        blank=True, decimal_places=10, max_digits=14, null=True
                    ),
                ),
                (
                    "orbit_class_type",
                    models.CharField(
                        blank=True, db_index=True, max_length=10, null=True
                    ),
                ),
                (
                    "orbit_class_description",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "neo",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="orbital_data",
                        to="astronomy.neo",
                    ),
                ),
            ],
            options={
                "db_table": "orbital_data",
            },
        ),
        migrations.CreateModel(
            name="CloseApproach",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("approach_date", models.DateField(db_index=True)),
                ("approach_datetime_utc", models.DateTimeField()),
                (
                    "velocity_km_s",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=12, null=True
                    ),
                ),
                (
                    "velocity_km_h",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=14, null=True
                    ),
                ),
                (
                    "miss_distance_km",
                    models.DecimalField(
                        blank=True,
                        db_index=True,
                        decimal_places=4,
                        max_digits=18,
                        null=True,
                    ),
                ),
                (
                    "miss_distance_au",
                    models.DecimalField(
                        blank=True, decimal_places=8, max_digits=12, null=True
                    ),
                ),
                ("orbiting_body", models.CharField(max_length=30)),
                (
                    "neo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="approaches",
                        to="astronomy.neo",
                    ),
                ),
            ],
            options={
                "db_table": "close_approach",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("neo", "approach_datetime_utc", "orbiting_body"),
                        name="uk_ca_unique",
                    )
                ],
            },
        ),
    ]
