# Generated by Django 6.1 on 2026-08-29 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("astronomy", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="exoplanet",
            name="equilibrium_temp_k",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
    ]
